name: diplodatos-mentorship
dependencies:
  - numpy==0.19
  - pandas
  - matplotlib
  - statsmodels
  - seaborn=0.11
  - nltk
  - keras
  - unidecode
  - scikit-learn==0.21.2
  - tensorflow
  - gensim
  - pip
  - pip:
    - mlflow
