name: diplodatos-mentorship
dependencies:
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - seaborn=0.11
  - nltk
  - keras
  - unidecode
  - scikit-learn
  - tensorflow
  - pip
  - pip:
    - mlflow
